import type { ThemePreset, ThemeState } from './theme-config.js';

/** Preset color themes — ported from Craft Agent bundled themes. */
export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'default',
    name: 'Craft',
    description: 'Clean purple-tinted neutral theme',
    supportedModes: ['light', 'dark'],
    shikiTheme: { light: 'github-light', dark: 'github-dark' },
    background: 'oklch(0.98 0.003 265)',
    foreground: 'oklch(0.185 0.01 270)',
    accent: 'oklch(0.58 0.22 293)',
    info: 'oklch(0.75 0.16 70)',
    success: 'oklch(0.55 0.17 145)',
    destructive: 'oklch(0.58 0.24 28)',
    dark: {
      background: 'oklch(0.2 0.005 270)',
      foreground: 'oklch(0.92 0.005 270)',
      accent: 'oklch(0.65 0.20 293)',
      info: 'oklch(0.70 0.16 70)',
      success: 'oklch(0.60 0.17 145)',
      destructive: 'oklch(0.70 0.19 22)',
    },
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Clean and professional',
    supportedModes: ['light', 'dark'],
    shikiTheme: { light: 'github-light', dark: 'github-dark' },
    background: '#ffffff',
    foreground: '#1f2328',
    accent: '#0969da',
    info: '#bf8700',
    success: '#1a7f37',
    destructive: '#cf222e',
    dark: {
      background: '#0d1117',
      foreground: '#e6edf3',
      accent: '#58a6ff',
      info: '#d29922',
      success: '#3fb950',
      destructive: '#f85149',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    description: 'Dark purple with bright accents',
    supportedModes: ['dark'],
    shikiTheme: { light: 'github-light', dark: 'dracula' },
    background: '#282a36',
    foreground: '#f8f8f2',
    accent: '#bd93f9',
    info: '#ffb86c',
    success: '#50fa7b',
    destructive: '#ff5555',
    dark: {
      background: '#282a36',
      foreground: '#f8f8f2',
      accent: '#bd93f9',
      info: '#ffb86c',
      success: '#50fa7b',
      destructive: '#ff5555',
    },
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin',
    description: 'Soothing pastel theme',
    supportedModes: ['light', 'dark'],
    shikiTheme: { light: 'catppuccin-latte', dark: 'catppuccin-mocha' },
    background: '#eff1f5',
    foreground: '#4c4f69',
    accent: '#8839ef',
    info: '#df8e1d',
    success: '#40a02b',
    destructive: '#d20f39',
    dark: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      accent: '#cba6f7',
      info: '#fab387',
      success: '#a6e3a1',
      destructive: '#f38ba8',
    },
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    description: 'Retro groove, earthy tones',
    supportedModes: ['light', 'dark'],
    shikiTheme: { light: 'github-light', dark: 'vitesse-dark' },
    background: '#fbf1c7',
    foreground: '#3c3836',
    accent: '#458588',
    info: '#d79921',
    success: '#98971a',
    destructive: '#cc241d',
    dark: {
      background: '#282828',
      foreground: '#ebdbb2',
      accent: '#83a598',
      info: '#fabd2f',
      success: '#b8bb26',
      destructive: '#fb4934',
    },
  },
  {
    id: 'ghostty',
    name: 'Ghostty',
    description: 'Default StyleDark theme from Ghostty terminal',
    supportedModes: ['dark'],
    shikiTheme: { light: 'github-light', dark: 'vitesse-dark' },
    background: '#292c33',
    foreground: '#ffffff',
    accent: '#83a5d6',
    info: '#e0af68',
    success: '#b7bd73',
    destructive: '#c55757',
    dark: {
      background: '#292c33',
      foreground: '#ffffff',
      accent: '#83a5d6',
      info: '#e0af68',
      success: '#b7bd73',
      destructive: '#c55757',
    },
  },
  {
    id: 'haze',
    name: 'Haze',
    description: 'Scenic background with glass panels',
    mode: 'scenic',
    backgroundImage: 'https://images.pexels.com/photos/764450/pexels-photo-764450.jpeg',
    supportedModes: ['dark'],
    shikiTheme: { dark: 'github-dark' },
    background: 'rgba(0, 0, 0, 0.4)',
    foreground: '#f5f5f7',
    accent: '#a78bfa',
    info: '#fbbf24',
    success: '#22c55e',
    destructive: '#ef4444',
    popoverSolid: '#2a2a2e',
  },
  {
    id: 'nord',
    name: 'Nord',
    description: 'Arctic, north-bluish, calm',
    supportedModes: ['light', 'dark'],
    shikiTheme: { light: 'github-light', dark: 'nord' },
    background: '#eceff4',
    foreground: '#2e3440',
    accent: '#5e81ac',
    info: '#ebcb8b',
    success: '#a3be8c',
    destructive: '#bf616a',
    dark: {
      background: '#2e3440',
      foreground: '#eceff4',
      accent: '#88c0d0',
      info: '#ebcb8b',
      success: '#a3be8c',
      destructive: '#bf616a',
    },
  },
  {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    description: 'Atom-inspired, balanced contrast',
    supportedModes: ['light', 'dark'],
    shikiTheme: { light: 'one-light', dark: 'one-dark-pro' },
    background: '#fafafa',
    foreground: '#383a42',
    accent: '#4078f2',
    info: '#c18401',
    success: '#50a14f',
    destructive: '#e45649',
    dark: {
      background: '#282c34',
      foreground: '#abb2bf',
      accent: '#61afef',
      info: '#e5c07b',
      success: '#98c379',
      destructive: '#e06c75',
    },
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'For night owls, reduced blue light',
    supportedModes: ['dark'],
    shikiTheme: { light: 'github-light', dark: 'night-owl' },
    background: '#011627',
    foreground: '#d6deeb',
    accent: '#82aaff',
    info: '#ecc48d',
    success: '#addb67',
    destructive: '#ef5350',
    dark: {
      background: '#011627',
      foreground: '#d6deeb',
      accent: '#82aaff',
      info: '#ecc48d',
      success: '#addb67',
      destructive: '#ef5350',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    description: 'Downtown Tokyo at night',
    supportedModes: ['dark'],
    shikiTheme: { light: 'github-light', dark: 'tokyo-night' },
    background: '#1a1b26',
    foreground: '#c0caf5',
    accent: '#7aa2f7',
    info: '#e0af68',
    success: '#9ece6a',
    destructive: '#f7768e',
    dark: {
      background: '#1a1b26',
      foreground: '#c0caf5',
      accent: '#7aa2f7',
      info: '#e0af68',
      success: '#9ece6a',
      destructive: '#f7768e',
    },
  },
  {
    id: 'solarized',
    name: 'Solarized',
    description: 'Precision colors, scientifically designed',
    supportedModes: ['light', 'dark'],
    shikiTheme: { light: 'solarized-light', dark: 'solarized-dark' },
    background: '#fdf6e3',
    foreground: '#657b83',
    accent: '#268bd2',
    info: '#b58900',
    success: '#859900',
    destructive: '#dc322f',
    dark: {
      background: '#002b36',
      foreground: '#839496',
      accent: '#268bd2',
      info: '#b58900',
      success: '#859900',
      destructive: '#dc322f',
    },
  },
  {
    id: 'rose-pine',
    name: 'Rosé Pine',
    description: 'Soho vibes, warm and elegant',
    supportedModes: ['light', 'dark'],
    shikiTheme: { light: 'rose-pine-dawn', dark: 'rose-pine' },
    background: '#faf4ed',
    foreground: '#575279',
    accent: '#907aa9',
    info: '#ea9d34',
    success: '#286983',
    destructive: '#b4637a',
    dark: {
      background: '#191724',
      foreground: '#e0def4',
      accent: '#c4a7e7',
      info: '#f6c177',
      success: '#31748f',
      destructive: '#eb6f92',
    },
  },
  {
    id: 'vitesse',
    name: 'Vitesse',
    description: 'Minimal and clean',
    supportedModes: ['light', 'dark'],
    shikiTheme: { light: 'vitesse-light', dark: 'vitesse-dark' },
    background: '#ffffff',
    foreground: '#393a34',
    accent: '#1e754f',
    info: '#b58900',
    success: '#1e754f',
    destructive: '#ab5959',
    dark: {
      background: '#121212',
      foreground: '#dbd7caee',
      accent: '#4d9375',
      info: '#caa75d',
      success: '#4d9375',
      destructive: '#cb7676',
    },
  },
  {
    id: 'pierre',
    name: 'Pierre',
    description: 'Clean, built for diffs',
    supportedModes: ['light', 'dark'],
    shikiTheme: { light: 'github-light', dark: 'github-dark' },
    background: '#ffffff',
    foreground: '#24292f',
    accent: '#009fff',
    info: '#fe8c2c',
    success: '#0dbe4e',
    destructive: '#fc2b73',
    dark: {
      background: '#0d1117',
      foreground: '#c9d1d9',
      accent: '#69b1ff',
      info: '#ffa359',
      success: '#5ecc71',
      destructive: '#ff678d',
    },
  },
];

export const THEME_PRESET_MAP = new Map(THEME_PRESETS.map((t) => [t.id, t]));

export function getThemePreset(id: string): ThemePreset | undefined {
  return THEME_PRESET_MAP.get(id);
}

export function getDefaultThemeState(): ThemeState {
  return { colorTheme: 'default', colorMode: 'system' };
}
